version: 2.1
jobs:
    unit-test:
        docker:
            - image: cimg/node:12.18.4
        steps:
            - checkout
            - run:
                name: Setup NPM env
                command: |
                    npm install
            - run:
                name: Run unit tests
                command: |
                    npm run test
    build-tests:
        docker:
            - image: cimg/base:stable-18.04
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Cypress Tester Image
                command: |
                    ls -lah ./
                    echo '^^^ ls current working directory ^^^'
                    echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
                    docker build -t temp-ci/cypress -f Dockerfile.cypress .
                # command: |
                #     echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
                #     docker build -t gerardrbentley/gar-brain:$TAG .
                #     echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
                #     docker push gerardrbentley/gar-brain:$TAG
            - run:
                name: Archive Docker Tar files
                command: |
                    docker save -o image_cypress.tar temp-ci/cypress
            - persist_to_workspace:
                root: .
                paths:
                    - ./image_cypress.tar
    build:
        docker:
            - image: cimg/base:stable-18.04
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Docker Image
                command: |
                    ls -lah ./
                    echo '^^^ ls current working directory ^^^'
                    echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
                    docker build -t gerardrbentley/gar-brain .
                # command: |
                #     echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
                #     docker build -t gerardrbentley/gar-brain:$TAG .
                #     echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
                #     docker push gerardrbentley/gar-brain:$TAG
            - run:
                name: Archive Docker Tar file
                command: docker save -o image.tar gerardrbentley/gar-brain
            - persist_to_workspace:
                root: .
                paths:
                    - ./image.tar
                    - ./docker-compose.ci.yml
    test-chrome:
        docker:
            - image: cimg/base:stable-18.04
        steps:
            - attach_workspace:
                at: /tmp/workspace
            - setup_remote_docker
            - run:
                name: Load archived Docker images
                command: |
                    ls -lah ./
                    echo '^^^ ls current working directory ^^^'
                    ls -lah /tmp/workspace
                    echo '^^^ ls /tmp/workspace ^^^'
                    docker load -i /tmp/workspace/image.tar
                    docker load -i /tmp/workspace/image_cypress.tar
            # - run: 
            #     name: Pull Cypress Included Image
            #     command: docker pull cypress/included:5.2.0
            - run: 
                name: Run E2E Chrome test
                command: docker-compose -f /tmp/workspace/docker-compose.ci.yml run e2e-chrome
orbs:
    heroku: circleci/heroku@1.2.2
workflows:
    heroku_deploy:
        jobs:
            - unit-test:
                filters:
                    branches:
                        only: main
            - build-tests:
                filters:
                    branches:
                        only: main
            - build:
                # requires:
                #     - unit-test
                filters:
                    branches:
                        only: main
            - test-chrome:
                requires:
                    - build
                    - build-tests
                filters:
                    branches:
                        only: main
            - heroku/deploy-via-git:
                requires:
                    - test-chrome
                    - unit-test
                filters:
                    branches:
                        only: main